### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by JohannesMP** [scrtwpns/mixbox#4]
While the license in the readme is fine, having a dedicated "LICENSE" file as is common practice would be nice :)

**Comment by virtualritz** [comment]
There is also code inside `mixbox.cpp`, to decode PNG, which looks like it is verbatim copied from [stb](https://github.com/nothings/stb) and was originally under either `MIT` or a public domain`unlicense`. Even assuming the authors choose the latter, I wonder if it is ‘kosher‘ to claim copyright of this.

I would suggest to move these parts into a separate source file and mark them exterior to the copyright claims to alleviate any legal issues in the future.

**Comment by Nolram12345** [comment]
Having a license file would absolutely be great - though, both the MIT and unlicense allow for sublicensing, so this is technically speaking legal.

**Comment by dromer** [comment]
Putting a proper license on this work would certainly be preferable.

Unfortunately the current "license notice" is not free software compatible, though.

**Comment by Nolram12345** [comment]
Its not free software compatible because this isn't free software.

**Comment by dromer** [comment]
> Its not ...
That's what I just said.

Just pointed out some "personal grief" with the decision ;)
Would've been nice if krita could get this, free pigment mixing for all!

Now it's just "study and weep" I suppose.

Interesting that they are taking the code dependency on stb as public domain and not even attributing to it.

**Comment by virtualritz** [comment]
@dromer you could just implement your own version of the paper from scratch.

**Comment by dromer** [comment]
Yup, "reference implementation" say, but don't put it in production ;)

**Comment by scrtwpns** [comment]
We added dedicated LICENSE file with CC BY-NC 4.0 license.

**Comment by dromer** [comment]
"CC BY-NC 4.0" is not a proper software license though.

It only covers "content" under "copyright" terms.

**Comment by joakin** [comment]
For dual licensing like it seems this is, probably releasing all these as GPL and LGPL, and having a comercial license , would be the equivalent to the CC BY-NC and commercial license.

Something like what Qt does:

> Qt for Application Development is dual-licensed under commercial and open source licenses. The commercial Qt license gives you the full rights to create and distribute software on your own terms without any open source license obligations. With the commercial license you also have access to the official Qt Support and close strategic relationship with The Qt Company to make sure your development goals are met.
> 
> Qt for Application Development is also available under GPL and LGPLv3 open source licenses. Qt tools and some libraries are only available under GPL. See the [comparison chart](https://www.qt.io/product/features?hsLang=en) for details. The Qt open source licensing is ideal for use cases such as open source projects with open source distribution, student/academic purposes, hobby projects, internal research projects without external distribution, or other projects where all [(L)GPL obligations](https://www1.qt.io/qt-licensing-terms/) can be met.

https://www.qt.io/licensing/

**Comment by joakin** [comment]
> "commercial license" is incompatible with the gpl, though

No it is not. The owners of the software can dual license it as they please. Any contributions to the GPL version would need a CLA though, to ensure the contributions can be released in the comercial license as well. 

See what I posted above of what Qt does:

> Qt for Application Development is dual-licensed under commercial and open source licenses. The commercial Qt license gives you the full rights to create and distribute software on your own terms without any open source license obligations.
> ...
> Qt for Application Development is also available under GPL and LGPLv3 open source licenses [...] The Qt open source licensing is ideal for use cases such as open source projects with open source distribution, student/academic purposes, hobby projects, internal research projects without external distribution [...]

This model would make it very easy for fully open source programs like Krita to be able to use the code because they are GPL compatible, and for Secret weapons to sell comercial licenses to propietary software products.


As it stands, software with a CC license which is meant for contents, I'm not sure if any projects would care to incorporate it due to the incompatibility with OSS licenses.

**Comment by davidak** [comment]
>Any contributions to the GPL version would need a CLA though, to ensure the contributions can be released in the comercial license as well.

yes, that way it would work

but contributors might not like that @scrtwpns makes money with their contribution and might not contribute. limiting the potential quality the project can achieve

**Comment by joakin** [comment]
The situation is the same right now with the CC-NC license. They are the
copyright owners of their own code which they licensed this way, but if
they get contributions they will be to the CC-NC codebase. They would not
be able to use those contributions without the permission of the authors to
release them in a different commercial license.

The only difference is that OSS projects will probably not use CC licensed
code because the license is not OSI compliant.

**Comment by joakin** [comment]
> If I'm not allowed to use the code commercially under the GPL, then the "dual license" is not compatible with the GPL.
> 

I'm not sure where you get this from. I did not say such a thing.

> Commercial use is 100% allowed under GPL terms. Under dual license typically fall proprietary applications, that need the additional licensing (see for instance with JUCE and Steinberg opensource licenses).
> 

Yes, exactly what I said.

> So, now we are stuck with a copyright notice and no software license at all.
> 
> Better hope for someone to reimplement this in a foss project then.

With this attitude you are not helping. You are wearing the maintainers down.

The authors did amazing work, published a free paper, gave a talk at a respected conference, and it looks like they have the intention to provide an open source version of their work in multiple languages. They also want to be able to sell comercial licenses for comercial software to earn and keep doing their great work.

There is a model for this, which is dual-licensing like I outlined above with the Qt case.

The hole would be any GPL licensed application that is paid, but those are rare and few between and the only way to make money is with services / distribution, because being GPL they can be built and distributed by someone else for free. So I would believe that dual-licensing would match their business model at the moment.

**Comment by dromer** [comment]
Yes I agree that they did fantastic work, it's just a shame that we cannot use it under free software terms.

"commercial" is a very broad umbrella as well. even if your project isn't commercial, linux distros often will not ship incompatible licensed material because they will sell physical copies. all the major distros tend to avoid such content. cc-nc prohibits use by free software communities in this way.
